version: '2'

services:

  tomcat:
    build: ./containers/tomcat
    image: oifyi_tomcat:latest
    ports:
      - "8888:8080"
    networks:
      - front-tier
      - back-tier

  oracle-xe:
    build: ./containers/oracle-xe
    image: oifyi_oracle-xe:latest
    shm_size: 2G
    ports:
      - "10022:22"
      - "11521:1521"
      - "18080:8080"
    networks:
      - back-tier

  maven:
    build: ../dev
    image: oifyi_maven:latest
    networks:
      - back-tier
    volumes:
      - ../dev:/app

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
