-- Generated by Oracle SQL Developer Data Modeler 4.1.3.901
--   at:        2016-10-20 10:43:44 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g




CREATE TABLE clients
  (
    id                         INTEGER NOT NULL ,
    raison_sociale             VARCHAR2 (100) NOT NULL ,
    forme_juridique            VARCHAR2 (20) NOT NULL ,
    siret                      VARCHAR2 (50) NOT NULL ,
    num_tva                    VARCHAR2 (50) ,
    RCS                        VARCHAR2 (50) ,
    adresse_numero             INTEGER ,
    adresse_rue                VARCHAR2 (100) NOT NULL ,
    adresse_cp                 INTEGER NOT NULL ,
    adresse_ville              VARCHAR2 (50) NOT NULL ,
    telephone                  INTEGER NOT NULL ,
    capital                    INTEGER ,
    ville_inscription          VARCHAR2 (50) ,
    representant_nom           VARCHAR2 (50) NOT NULL ,
    representant_fonction      VARCHAR2 (50) NOT NULL ,
    respo_client_tel           INTEGER ,
    contact_achats_nom         VARCHAR2 (50) ,
    contact_achats_tel         INTEGER ,
    respo_fournisseur_nom      VARCHAR2 (50) ,
    respo_fournisseur_fonction VARCHAR2 (50)
  ) ;
ALTER TABLE clients ADD CONSTRAINT clients_PK PRIMARY KEY ( id ) ;


CREATE TABLE consultant
  (
    id       INTEGER NOT NULL ,
    nom      VARCHAR2 (50) NOT NULL ,
    prenom   VARCHAR2 (50) NOT NULL ,
    username VARCHAR2 (50) NOT NULL ,
    password VARCHAR2 (50) NOT NULL ,
    role_id  INTEGER NOT NULL
  ) ;
ALTER TABLE consultant ADD CONSTRAINT consultant_PK PRIMARY KEY ( id ) ;


CREATE TABLE cra_jour
  (
    id_cramois     INTEGER NOT NULL ,
    jour           DATE NOT NULL ,
    heures_travail INTEGER NOT NULL
  ) ;
ALTER TABLE cra_jour ADD CONSTRAINT cra_jour_PK PRIMARY KEY ( id_cramois, jour ) ;


CREATE TABLE cra_mois
  (
    id            INTEGER NOT NULL ,
    mission_id    INTEGER NOT NULL ,
    consultant_id INTEGER NOT NULL ,
    mois_annee    DATE NOT NULL ,
    status_id     INTEGER NOT NULL
  ) ;
ALTER TABLE cra_mois ADD CONSTRAINT CRA_PK PRIMARY KEY ( id ) ;
ALTER TABLE cra_mois ADD CONSTRAINT cra_mois__UN UNIQUE ( mission_id , consultant_id , mois_annee ) ;


CREATE TABLE mapping_url_fichier
  (
    page    VARCHAR2 (30) NOT NULL ,
    "mode"  VARCHAR2 (30) NOT NULL ,
    fichier VARCHAR2 (30) NOT NULL
  ) ;
ALTER TABLE mapping_url_fichier ADD CONSTRAINT mapping_url_fichier_PK PRIMARY KEY ( page, "mode" ) ;


CREATE TABLE mission
  (
    id             INTEGER NOT NULL ,
    nom            VARCHAR2 (50) NOT NULL ,
    numero_contrat INTEGER ,
    clients_id     INTEGER NOT NULL ,
    date_debut     DATE NOT NULL ,
    date_fin       DATE ,
    REFERENCE      VARCHAR2
    --  ERROR: VARCHAR2 size not specified
    NOT NULL ,
    poste_mission               VARCHAR2 (50) ,
    adresse_facturation         VARCHAR2 (100) ,
    modalite_reglement          VARCHAR2 (50) NOT NULL ,
    respect_preavis_resiliation VARCHAR2 (50) NOT NULL ,
    lieu_execution              VARCHAR2 (50) ,
    condition_renouvellement    VARCHAR2 (50)
  ) ;
ALTER TABLE mission ADD CONSTRAINT Missions_PK PRIMARY KEY ( id ) ;


CREATE TABLE mission_consultant
  (
    consultant_id INTEGER NOT NULL ,
    mission_id    INTEGER NOT NULL ,
    prix          INTEGER ,
    tjm           INTEGER NOT NULL
  ) ;
ALTER TABLE mission_consultant ADD CONSTRAINT mission_consultant_PK PRIMARY KEY ( consultant_id, mission_id ) ;


CREATE TABLE parametrage
  (
    libelle VARCHAR2 (30 CHAR) NOT NULL ,
    valeur  VARCHAR2 (30 CHAR) NOT NULL
  ) ;
ALTER TABLE parametrage ADD CONSTRAINT parametrage_PK PRIMARY KEY ( libelle ) ;


CREATE TABLE role
  ( id INTEGER NOT NULL , libelle VARCHAR2 (30) NOT NULL
  ) ;
ALTER TABLE role ADD CONSTRAINT role_PK PRIMARY KEY ( id ) ;


CREATE TABLE status_cra
  (
    id      INTEGER NOT NULL ,
    libelle VARCHAR2
    --  ERROR: VARCHAR2 size not specified
    NOT NULL
  ) ;
ALTER TABLE status_cra ADD CONSTRAINT status_cra_PK PRIMARY KEY ( id ) ;


ALTER TABLE consultant ADD CONSTRAINT consultant_role_FK FOREIGN KEY ( role_id ) REFERENCES role ( id ) ;

ALTER TABLE cra_jour ADD CONSTRAINT cra_jour_cra_mois_FK FOREIGN KEY ( id_cramois ) REFERENCES cra_mois ( id ) ;

ALTER TABLE cra_mois ADD CONSTRAINT cra_mois_consultant_FK FOREIGN KEY ( consultant_id ) REFERENCES consultant ( id ) ;

ALTER TABLE cra_mois ADD CONSTRAINT cra_mois_missions_FK FOREIGN KEY ( mission_id ) REFERENCES mission ( id ) ;

ALTER TABLE cra_mois ADD CONSTRAINT cra_mois_status_cra_FK FOREIGN KEY ( status_id ) REFERENCES status_cra ( id ) ;

--  ERROR: FK name length exceeds maximum allowed length(30)
ALTER TABLE mission_consultant ADD CONSTRAINT mission_consultant_consultant_FK FOREIGN KEY ( consultant_id ) REFERENCES consultant ( id ) ;

ALTER TABLE mission_consultant ADD CONSTRAINT mission_consultant_mission_FK FOREIGN KEY ( mission_id ) REFERENCES mission ( id ) ;

ALTER TABLE mission ADD CONSTRAINT missions_clients_FK FOREIGN KEY ( clients_id ) REFERENCES clients ( id ) ;


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            10
-- CREATE INDEX                             0
-- ALTER TABLE                             19
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   3
-- WARNINGS                                 0

