INSERT INTO ROLE (LIBELLE) VALUES ('Admin');
INSERT INTO ROLE (LIBELLE) VALUES ('Direction');
INSERT INTO ROLE (LIBELLE) VALUES ('Equipe Commerciale');
INSERT INTO ROLE (LIBELLE) VALUES ('Responsable de pole');
INSERT INTO ROLE (LIBELLE) VALUES ('Independant');
INSERT INTO ROLE (LIBELLE) VALUES ('Salarie');
INSERT INTO ROLE (LIBELLE) VALUES ('Lambda');