INSERT INTO CONSULTANT (NOM, PRENOM, USERNAME, PASSWORD, ROLE_ID) VALUES ('Admin', 'Admin', 'Admin', '1234', 1);
INSERT INTO CONSULTANT (NOM, PRENOM, USERNAME, PASSWORD, ROLE_ID) VALUES ('Direction', 'Direction', 'Direction', '1234', 2);
INSERT INTO CONSULTANT (NOM, PRENOM, USERNAME, PASSWORD, ROLE_ID) VALUES ('Commerciale', 'Commerciale', 'Commerciale', '1234', 3);
INSERT INTO CONSULTANT (NOM, PRENOM, USERNAME, PASSWORD, ROLE_ID) VALUES ('Responsable de pole', 'Responsable de pole', 'Responsable de pole', '1234', 4);
INSERT INTO CONSULTANT (NOM, PRENOM, USERNAME, PASSWORD, ROLE_ID) VALUES ('Independant', 'Independant', 'Independant', '1234', 5);
INSERT INTO CONSULTANT (NOM, PRENOM, USERNAME, PASSWORD, ROLE_ID) VALUES ('Salarie', 'Salarie', 'Salarie', '1234', 6);
INSERT INTO CONSULTANT (NOM, PRENOM, USERNAME, PASSWORD, ROLE_ID) VALUES ('Lambda', 'Lambda', 'Lambda', '1234', 7);

