INSERT INTO CONSULTANT_ROLE (ID_CONSULTANT, ID_ROLE) VALUES (1, 1);
INSERT INTO CONSULTANT_ROLE (ID_CONSULTANT, ID_ROLE) VALUES (1, 2);
INSERT INTO CONSULTANT_ROLE (ID_CONSULTANT, ID_ROLE) VALUES (2, 2);
INSERT INTO CONSULTANT_ROLE (ID_CONSULTANT, ID_ROLE) VALUES (3, 3);
INSERT INTO CONSULTANT_ROLE (ID_CONSULTANT, ID_ROLE) VALUES (4, 4);
INSERT INTO CONSULTANT_ROLE (ID_CONSULTANT, ID_ROLE) VALUES (5, 5);
INSERT INTO CONSULTANT_ROLE (ID_CONSULTANT, ID_ROLE) VALUES (6, 6);