INSERT INTO CONSULTANT (NOM, PRENOM, USERNAME, PASSWORD) VALUES ('Admin', 'Admin', 'Admin', '1234');
INSERT INTO CONSULTANT (NOM, PRENOM, USERNAME, PASSWORD) VALUES ('Direction', 'Direction', 'Direction', '1234');
INSERT INTO CONSULTANT (NOM, PRENOM, USERNAME, PASSWORD) VALUES ('Commerciale', 'Commerciale', 'Commerciale', '1234');
INSERT INTO CONSULTANT (NOM, PRENOM, USERNAME, PASSWORD) VALUES ('Responsable de pole', 'Responsable de pole', 'Responsable de pole', '1234');
INSERT INTO CONSULTANT (NOM, PRENOM, USERNAME, PASSWORD) VALUES ('Independant', 'Independant', 'Independant', '1234');
INSERT INTO CONSULTANT (NOM, PRENOM, USERNAME, PASSWORD) VALUES ('Salarie', 'Salarie', 'Salarie', '1234');

INSERT INTO CONSULTANT (NOM, PRENOM, USERNAME, PASSWORD) VALUES ('Neymar', 'Jean', 'JeanAiMarre', '1234');
INSERT INTO CONSULTANT (NOM, PRENOM, USERNAME, PASSWORD) VALUES ('Peuplu', 'Jean', 'Jpp', '1234');
INSERT INTO CONSULTANT (NOM, PRENOM, USERNAME, PASSWORD) VALUES ('Rumen', 'Carl', 'CRumen', '1234');
INSERT INTO CONSULTANT (NOM, PRENOM, USERNAME, PASSWORD) VALUES ('Aroide', 'Paul', 'Pola', '1234');
INSERT INTO CONSULTANT (NOM, PRENOM, USERNAME, PASSWORD) VALUES ('Tomi', 'Anna', 'Annatomi', '1234');
INSERT INTO CONSULTANT (NOM, PRENOM, USERNAME, PASSWORD) VALUES ('Kolick', 'Al', 'kolickal', '1234');