INSERT INTO DROITS_PAGES (ID_PAGE, ID_ROLE) VALUES (9, 1);
INSERT INTO DROITS_PAGES (ID_PAGE, ID_ROLE) VALUES (9, 2);
INSERT INTO DROITS_PAGES (ID_PAGE, ID_ROLE) VALUES (9, 3);
INSERT INTO DROITS_PAGES (ID_PAGE, ID_ROLE) VALUES (9, 4);
INSERT INTO DROITS_PAGES (ID_PAGE, ID_ROLE) VALUES (9, 5);
INSERT INTO DROITS_PAGES (ID_PAGE, ID_ROLE) VALUES (9, 6);
