INSERT INTO CONSULTANT (NOM, PRENOM, USERNAME, PASSWORD, ROLE_ID) VALUES ('LBP', 'Erwan', 'panomanix', '1234', 1);
INSERT INTO CONSULTANT (NOM, PRENOM, USERNAME, PASSWORD, ROLE_ID) VALUES ('Nandillon', 'Alexis', 'croute', '1234', 1);
INSERT INTO CONSULTANT (NOM, PRENOM, USERNAME, PASSWORD, ROLE_ID) VALUES ('Bob', 'léponge', 'boble', '1234', 6);
